language: java
jdk:
- oraclejdk8
services:
- rabbitmq
install: ''
script:
- mvn clean deploy --settings settings.xml -B -V
after_success:
- mvn clean test jacoco:report coveralls:report
env:
  global:
  - secure: GZTdP3ij3zpx4isJ4IH6baurpkt8jM/v109YsNxFxXPvkk6Cv2y3ohxeyINo/5c5O9skpf4rII5BXpMd9DqYhtQebIKK4tdvoGZbMUcq3dfk+o4LkoJKGtYqgFACooCQ7Z4IDTsW/i+jWCOnptcV+JHAb5FFO6kIR8xfqPiGMpY=
  - secure: juuiB0BqUWLCPFQEol+j6Ulk/bv4lii8mAUIaiUOs7xfbqeFHsrP1jp5WONwjm2Gq2PrpMl42G2MVa6VhNm0l2EqgF9SRinxhEH9/Hu+OqCRWks7CCgZhdZ+DzDCdbIjsLwf+BR/nwIXOgVU8N6ZsbU1h6FoWZwqMbty/SBLgYs=
